### ISSUE TITLE
unable to load h5 file

### ISSUE THREAD

**Issue by kailaw138** [BiodataMiningGroup/quimbi#13]
**Attempt 1:**

I have installed set up a development server with node ver. 20.10.0 in windows, the demo txt data can be loaded, 
However, h5 data, neither the demo msi_5d_g3_r0_va_barley_101_peaks_karin.h5, nor other .h5 files processed with ProViM, could be loaded. The procedure as follow:

in running node (from Node.js command prompt), legacy OpenSSL provider is enabled, with set NODE_OPTIONS=--openssl-legacy-provider

then  npm run start:dev

starts a node based webpack development server at localhost:8080

 .txt data could be loaded .... but not h5 files

**Attempt 2:**

An alternative method is set up with xampp 8.2.12-0, with Apache started running

cmd to the dist/index.html, then php -S localhost:8000

http://localhost:8000 in browser, load

However, neither the .txt nor the .h5 demo data load

Please give me the instructions to make it work.

Many thanks.

**Comment by annzu** [comment]
QUIMBI cannot read h5 files, but uses its own file format, which consists of a .txt and pngs.  
To convert the h5 file, please follow the instructions under "Data Creation" (https://github.com/BiodataMiningGroup/quimbi#data-creation). 
Then enter the .txt in QUIMBI to start the application.

**Comment by kailaw138** [comment]
Thanks - problem solved. 

The instructions would have been clearer if it also has a "Local Version (without Docker)" section.
